### ISSUE TITLE
Wireguard server not working

### ISSUE THREAD

**Issue by nsimanskij** [complexorganizations/wireguard-install#100]
Hello. Few days ago I try to install wireguard on VPS server with Ubuntu 18.04 64bit. Instalation was successful and wireguard working fine with no erross, but then I try install on another VPS but in differnt server location I have some issues. After script finished instalation I see this:

Client Config --> /etc/wireguard/clients/git-wg0.conf
204
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service → /lib/systemd/system/wg-quick@.service.
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
27 Jul 19:15:33 ntpdate[7791]: adjust time server 193.219.61.120 offset -0.000404 sec

In systemctl status wg-quick@wg0.service I see this:

~
 ESCOD
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/lib/systemd/system/wg-quick@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-07-27 19:15:25 CEST; 6min ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg-quick.8
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg.8
  Process: 7741 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=127)
 Main PID: 7741 (code=exited, status=127)

Jul 27 19:15:25 gitukas wg-quick[7741]: [#] wg setconf wg0 /dev/fd/63
Jul 27 19:15:25 gitukas wg-quick[7741]: [#] ip -4 address add 10.8.0.1/24 dev wg0
Jul 27 19:15:25 gitukas wg-quick[7741]: [#] ip -6 address add fd42:42:42::1/64 dev wg0
Jul 27 19:15:25 gitukas wg-quick[7741]: [#] ip link set mtu 1420 up dev wg0
Jul 27 19:15:25 gitukas wg-quick[7741]: [#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j A
Jul 27 19:15:25 gitukas wg-quick[7741]: /usr/bin/wg-quick: line 248: iptables: command not found
Jul 27 19:15:25 gitukas wg-quick[7741]: [#] ip link delete dev wg0
Jul 27 19:15:25 gitukas systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=127/n/a
Jul 27 19:15:25 gitukas systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Jul 27 19:15:25 gitukas systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.
~
Tell me please what could be the problem?

**Comment by prajwalkoirala23** [comment]
did u recently update the server or upgrade the server?

**Comment by nsimanskij** [comment]
I do update, then upgrade

**Comment by prajwalkoirala23** [comment]
@nsimanskij 
Do these commands and please post.
`sudo dpkg-reconfigure wireguard-dkms`
`sudo modprobe wireguard`

**Comment by prajwalkoirala23** [comment]
@nsimanskij
any update?

**Comment by nsimanskij** [comment]
Sorry dont try yet :( Then I will have time, I will try and reply to you. Thanks for answering

**Comment by prajwalkoirala23** [comment]
> Sorry dont try yet :( Then I will have time, I will try and reply to you. Thanks for answering

ok
