### ISSUE TITLE
 wg-quick@wg0.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by man-in-the-middle** [complexorganizations/wireguard-install#103]
Hi
First of all thank you for really nice script.

Issie:
#After install wg service dont start

> Job for wg-quick@wg0.service failed because the control process exited with erro                                                               r code.
systemctl status wg-quick@wg0.service
wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
 Loaded: loaded (/lib/systemd/system/wg-quick@.service; indirect; vendor prese
 Active: failed (Result: exit-code) since Sun 2019-09-01 08:28:41 UTC; 34s ago
 Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg-quick.8
           https://git.zx2c4.com/WireGuard/about/src/tools/man/wg.8
  Process: 11369 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=2)
 Main PID: 11369 (code=exited, status=2)
systemd[1]: Starting WireGuard via wg-quick(8)
wg-quick[11369]: [#] [#] ip link add wg0 type wireguard
wg-quick[11369]: [#] wg setconf wg0 /dev/fd/63
wg-quick[11369]: [#] ip -4 address add 10.8.0.1/24 dev wg0
wg-quick[11369]: [#] ip -6 address add fd42:42:42::1/64 dev wg0
wg-quick[11369]: RTNETLINK answers: Permission denied
wg-quick[11369]: [#] ip link delete dev wg0
systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, statu
systemd[1]:  wg-quick@wg0.service: Failed with result 'exit-code'.
systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0. 
> 

AWS EC2
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1044-aws x86_64)

**Comment by ThePigPeppa** [comment]
```
sudo dpkg-reconfigure wireguard-dkms
sudo modprobe wireguard
```
