### ISSUE TITLE
/etc/resolv.conf

### ISSUE THREAD

**Issue by ewan2395** [complexorganizations/wireguard-install#109]
The uninstallation process adds 'nameserver 127.0.0.53' and then write protects '/etc/resolve.conf' with 'chattr +i' which breaks DNS resolution on systems such as Debian. This occurs even if no DNS features were installed during the running of the server script.

Backing up the original resolve.conf and then restoring it during the uninstall process would be a better method for multi-platform support.

**Comment by Prajwal-Koirala** [comment]
ill make this change now.

you're a good person for bringing up this issue.

**Comment by Prajwal-Koirala** [comment]
Please create a pull request.

**Comment by Joseph-Zaino** [comment]
Thanks for this. I spun up a Lightsail instance on AWS and ran your script. I had the issues with the script failing, but I haven't figured out how. I erased the /etc/wireguard/wg... file so the script thought it wasn't installed. After making resolv.conf not imutable and adding 8.8.8.8 to the resolv.conf to get things going again the reinstall worked. I suspect something went wrong on the original install as the instance needed packages that are different than what your script calls for. apt update &&apt upgrade and a reboot everything worked. Perhaps a check for failure would be  a good idea on the apt commands before you lock down resolv.conf and the rest doesn't work?

**Comment by Prajwal-Koirala** [comment]
@ewan2395 its been fixed.


@Joseph-Zaino please use the latest version of the script and post back.
The issues you were seeing were all fixed.
