### ISSUE TITLE
Centos DNS Resolve: Name or service not known

### ISSUE THREAD

**Issue by Padandish** [complexorganizations/wireguard-install#110]
Hi Dears,
I used this script and very nice, thanks.
Last day, i used with default values (Unbound installed by script)on CentOS Linux release 7.7.1908 (Core).
after completed process, when client connect to server didn't have internet access through by server.
I check it access by ip and DNS not worked!

Server:
ping: google.com: Name or service not known

How can i fix it?

**Comment by Padandish** [comment]
WoW,
I checked again, when i disable my firewall, everything OK!
How can i create firewall roll?

**Comment by Prajwal-Koirala** [comment]
`yum install iptables firewall-cmd -y`

Use that...

**Comment by Padandish** [comment]
thanks, that is installed, but i need help which role to add?

**Comment by ImLuke954** [comment]
@Padandish Did you manage to solve this issue? I am having the same problem

**Comment by Prajwal-Koirala** [comment]
@ImLuke954 I am taking a look into this and will have a fix within 24 hours.

Thank you for your patience.

**Comment by Prajwal-Koirala** [comment]
@Padandish @ImLuke954 

It's been fixed on the script.

Please test and post back.

Thanks

**Comment by alpineboi20** [comment]
I just Ran into this issue too & the above fix worked. However, It looks like its not fixed in the script. It fails to add interface: 127.0.0.1 to unbound.conf. If it helps I'm using CentOS 7 on a 25gb Vultr instance.
