### ISSUE TITLE
Make better use of variables (server script)

### ISSUE THREAD

**Issue by Fastidious** [complexorganizations/wireguard-install#111]
Even though variables are defined on the server install script, they are not used throughout (unbound has hard coded IP, for example). It would make sense to add the ability to set variables, which are used accordingly throughout the entire script.

**Comment by Prajwal-Koirala** [comment]
PULL..

See on GitHub people talk alot and make less Pull Request so I wanna see less talking and making more Pull Requests.

**Comment by Fastidious** [comment]
@Prajwal-Koirala I will do my best to send in a PR. Understand that many people on GitHub aren't coders (I am within that group), yet they can spot issues, and recommend improvements.

**Comment by Prajwal-Koirala** [comment]
> @Prajwal-Koirala I will do my best to send in a PR. Understand that many people on GitHub aren't coders (I am within that group), yet they can spot issues, and recommend improvements.

Ill add this soon.
