### ISSUE TITLE
Hetzner cloud (Solved)

### ISSUE THREAD

**Issue by ardipa** [complexorganizations/wireguard-install#120]
Please support hetzner cloud.
 it's based on KVM so there shouldn't be any problem supporting it!

**Comment by Prajwal-Koirala** [comment]
@ardipa 
Please make a pull.

**Comment by ardipa** [comment]
> @ardipa
> Please make a pull.
> 
> If you use Ubuntu it will work but it won't work on Debian for Hetzner

Dear Prajwal,
I'm using Centos cloud  from hetzner, Do you confirm that your wireguard script works with hetzner Centos?

Thank you

**Comment by Prajwal-Koirala** [comment]
Hello,
I am not sure, can u please check and report back.
Prajwal

**Comment by ardipa** [comment]
Ok, I will inform you :)

**Comment by Prajwal-Koirala** [comment]
can u please try the latest version of the script, it should work on centos on `Hetzner`

**Comment by Prajwal-Koirala** [comment]
@ardipa 

If your running CentOS 8

run this after installing the script.


```
$ sudo yum install epel-release
$ sudo yum config-manager --set-enabled PowerTools
$ sudo yum copr enable jdoss/wireguard
$ sudo yum install wireguard-dkms wireguard-tools
```

**Comment by ardipa** [comment]
Dear Prajwal,

Hetzner Centos 7= not working
Hetzner Centos 8= not working

**Comment by ardipa** [comment]
Dear Prajwal,
I can give you hetzner Centos 8 cloud so you can test and process wireguard.
Please inform me if you have time and interested.

Regards

**Comment by Prajwal-Koirala** [comment]
i have `Hetzner`
please try this.
```
wget https://raw.githubusercontent.com/complexorganizations/wireguard-install/master/wireguard-server.sh -P /etc/wireguard/
bash /etc/wireguard/wireguard-server.sh
sudo yum install epel-release
sudo yum config-manager --set-enabled PowerTools
sudo yum copr enable jdoss/wireguard
sudo yum install wireguard-dkms wireguard-tools
```

Please reboot after doing this and should work/

**Comment by ardipa** [comment]
> i have `Hetzner`
> please try this.
> 
> ```
> wget https://raw.githubusercontent.com/complexorganizations/wireguard-install/master/wireguard-server.sh -P /etc/wireguard/
> bash /etc/wireguard/wireguard-server.sh
> sudo yum install epel-release
> sudo yum config-manager --set-enabled PowerTools
> sudo yum copr enable jdoss/wireguard
> sudo yum install wireguard-dkms wireguard-tools
> ```
> 
> Please reboot after doing this and should work/

Hi,
I did it exactly on new hetzner centos 8 but it didn't work. So I installed web cockpit to diagnosis the problem, here is the results:

![Capture](https://user-images.githubusercontent.com/48614510/72930663-afe76e00-3d71-11ea-8e7e-0de0e30bd750.PNG)

![screencapture-95-217-14-5-9090-system-logs-2020-01-22-23_51_43](https://user-images.githubusercontent.com/48614510/72930912-2edca680-3d72-11ea-90c1-04ace6e70329.jpg)

**Comment by Prajwal-Koirala** [comment]
can you create a new server and post the ip here with this SSH key.

```
    mkdir -p /root/.ssh
    chmod 600 /root/.ssh
    echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJouQKvkIhLoCyE1lPheITbyIB6ZyEOmAY6e5jEhX6B prajwalkoirala23@protonmail.com' > /root/.ssh/authorized_keys
    chmod 700 /root/.ssh/authorized_keys
    sed -i 's|#PasswordAuthentication yes|PasswordAuthentication no|' /etc/ssh/sshd_config
    sed -i 's|#Port 22|Port 22|' /etc/ssh/sshd_config
    sudo /etc/init.d/ssh restart
```

SSH Key:
`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJouQKvkIhLoCyE1lPheITbyIB6ZyEOmAY6e5jEhX6B prajwalkoirala23@protonmail.com`

**Comment by ardipa** [comment]
Dear Prajwal,

I don't know how to use SSH key you provided for me.
Please give me an email address so I send you new hetzner centos8 root/password for your tests.

**Comment by Prajwal-Koirala** [comment]
> Dear Prajwal,
> 
> I don't know how to use SSH key you provided for me.
> 
> I will create new hetzner centos8 cloud and will send you credentials, Please give me an email address.
> 
> Is "[prajwalkoirala23@protonmail.com](mailto:prajwalkoirala23@protonmail.com)" ok to send credentials?

sure.

**Comment by ardipa** [comment]
credentials sent, Thank you :)

**Comment by Prajwal-Koirala** [comment]
```
wget https://raw.githubusercontent.com/complexorganizations/wireguard-install/master/wireguard-server.sh -P /etc/wireguard/
chmod +x /etc/wireguard/wireguard-server.sh
HEADLESS_INSTALL=y ./etc/wireguard/wireguard-server.sh
reboot
sudo yum install epel-release
sudo yum config-manager --set-enabled PowerTools
sudo yum copr enable jdoss/wireguard
sudo yum install wireguard-dkms wireguard-tools
reboot
wg
```

Please use these commands on CentOS

**Comment by ardipa** [comment]
1- typo:
[root@centos8 ~]# HEADLESS_INSTALL=y ./etc/wireguard/wireguard-server.sh
-bash: ./etc/wireguard/wireguard-server.sh: No such file or directory

Should be: **HEADLESS_INSTALL=y /etc/wireguard/wireguard-server.sh**

2- Still not working, I used my android device to scan QR code but nothing sent or receive!!

Any idea?

I sent you new vps, right now. hope it helps

**Comment by Prajwal-Koirala** [comment]
Let me know.

**Comment by ardipa** [comment]
> Let me know.

Dear Prajwal,

1- typo:
[root@centos8 ~]# HEADLESS_INSTALL=y ./etc/wireguard/wireguard-server.sh
-bash: ./etc/wireguard/wireguard-server.sh: No such file or directory

Should be: HEADLESS_INSTALL=y /etc/wireguard/wireguard-server.sh

2- Still not working, I used my android device to scan QR code but nothing sent or receive!!

Any idea?

I rebuilt the vps and sent you, right now. hope it helps

**Comment by Prajwal-Koirala** [comment]
Can u reboot the VPS and than let me know

**Comment by Prajwal-Koirala** [comment]
> > Let me know.
> 
> Dear Prajwal,
> 
> 1- typo:
> [root@centos8 ~]# HEADLESS_INSTALL=y ./etc/wireguard/wireguard-server.sh
> -bash: ./etc/wireguard/wireguard-server.sh: No such file or directory
> 
> Should be: HEADLESS_INSTALL=y /etc/wireguard/wireguard-server.sh
> **No . (dot) before /etc/**
> 
> 2- Still not working, I used my android device to scan QR code but nothing sent or receive!!
> 
> Any idea?
> 
> I rebuilt the vps and sent you, right now. hope it helps

Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal

**Comment by ardipa** [comment]
Hello Dear Prajwal,

It takes me some time to figure out what makes Hetzner Cloud not working with your shell script!
This solution is for "Hetzner CentOS 7/8" Only, but you may test it for other distribution:

**The major problem which Hetzner Cloud not working with your Wireguard script is that "Kernel Headers" are not installed!!**

So before running your Wireguard script, user should do as follow:
1- yum update
2- yum install kernel-devel
3- reboot

Now run Wireguard Script and everything must be OK :)

Regards,
ardipa

**Comment by Prajwal-Koirala** [comment]
Hey can u create a new VPS and try the latest version of the script??

I added headers already.

**Comment by ardipa** [comment]
> Hey can u create a new VPS and try the latest version of the script??
> 
> I added headers already.

Hi,
Sure :)

**Comment by ardipa** [comment]
> Hey can u create a new VPS and try the latest version of the script??
> 
> I added headers already.

Hi,
Sure :)

**Comment by Prajwal-Koirala** [comment]
> > Hey can u create a new VPS and try the latest version of the script??
> > I added headers already.
> 
> Hi,
> Sure :)

please don't do anything manually.

just let the script take care of it, also there are multiple debugging options so we can easily figure out what went wrong.

**Comment by Prajwal-Koirala** [comment]
also please dont use unbound.

**Comment by Prajwal-Koirala** [comment]
Hey, If you don't have time for this its fine, i have the rest of the day free.
Ill get this fixed by today.
also

if you manage to find a fix before me just make a pull.

**Comment by Prajwal-Koirala** [comment]
Solved.
```
sudo dkms autoinstall
```

if anyone still has any issues please use that command after using the script.
