### ISSUE TITLE
Centos DNS Resolve Still Broken.

### ISSUE THREAD

**Issue by alpineboi20** [complexorganizations/wireguard-install#123]
Hi, CentOS DNS Resolve is still broken after installing the script. The script fails to add "interface: 127.0.0.1" to the unbound.conf file. If it helps I'm using a fresh installation of CentOS 7 on a 25gb Vultr instance. Let me know if you need me to test anything.

Thanks

**Comment by Prajwal-Koirala** [comment]
already fixed.

**Comment by alpineboi20** [comment]
> 
> 
> already fixed.
> 
> fixed an issue within 24 sec of creation.

Damn that was fast. Thank you, much appreciated.

**Comment by Prajwal-Koirala** [comment]
> > already fixed.
> > fixed an issue within 24 sec of creation.
> 
> Damn that was fast. Thank you, much appreciated.

Hello,
Please feel free to fork and star this repository.
Prajwal
