### ISSUE TITLE
Hetzner cloud

### ISSUE THREAD

**Issue by tcassaert** [complexorganizations/wireguard-install#124]
Is there a specific reason why Hetzner Cloud would not be listed as supported? I've tried out the script on a Hetzner VPS, connected my phone and everythings seems alright.

**Comment by Prajwal-Koirala** [comment]
It has a success rate of about 50% on `Hetzner` sometimes it works and sometimes it doesn't need a little more R&D for official support.

**Comment by Prajwal-Koirala** [comment]
Hey,
If you have any fix for it, I am open to it.
- Prajwal

**Comment by ardipa** [comment]
Hello Dear Prajwal,

It takes me some time to figure out what makes Hetzner Cloud not working with your shell script!
This solution is for "Hetzner CentOS 7/8" Only, but you may test it for other distribution:

**The major problem which Hetzner Cloud not working with your Wireguard script is that "Kernel Headers" are not installed!!**

So before running your Wireguard script, user should do as follow:
1- yum update
2- yum install kernel-devel
3- reboot

Now run Wireguard Script and everything must be OK :)

Regards,
ardipa
