### ISSUE TITLE
CentOS: Client Can't Connect to Server, without adding rules to Firewalld.

### ISSUE THREAD

**Issue by alpineboi20** [complexorganizations/wireguard-install#125]
Not sure if it is intended for the user to add their own firewall rules, but would it be possible to add the below rules to the script, to allow connection through the firewall?

firewall-cmd --permanent --zone=public --add-port=51820/udp  #Or Chosen Port other than 51820.
firewall-cmd --permanent --zone=public --add-port=53/udp
firewall-cmd --permanent --add-masquerade
firewall-cmd --reload

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-install/blob/master/wireguard-server.sh#L645
```
PostUp = iptables -A FORWARD -i $WIREGUARD_PUB_NIC -j ACCEPT; iptables -t nat -A POSTROUTING -o $SERVER_PUB_NIC -j MASQUERADE; ip6tables -A FORWARD -i $WIREGUARD_PUB_NIC -j ACCEPT; ip6tables -t nat -A POSTROUTING -o $SERVER_PUB_NIC -j MASQUERADE; iptables -A INPUT -s $PRIVATE_SUBNET_V4 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
PostDown = iptables -D FORWARD -i $WIREGUARD_PUB_NIC -j ACCEPT; iptables -t nat -D POSTROUTING -o $SERVER_PUB_NIC -j MASQUERADE; ip6tables -D FORWARD -i $WIREGUARD_PUB_NIC -j ACCEPT; ip6tables -t nat -D POSTROUTING -o $SERVER_PUB_NIC -j MASQUERADE; iptables -D INPUT -s $PRIVATE_SUBNET_V4 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
```

We already have Iptables rules in the `wg0.conf` the file we don't need to add those.

**Comment by alpineboi20** [comment]
I'm using a 25gb vultr instance using CentOS 7 & without the above commands it won't let me connect.
I can spin you up a new instance if you want to try it ?

**Comment by Prajwal-Koirala** [comment]
yes please.

**Comment by alpineboi20** [comment]
No problem do you have a temp email or a temp email, so i can send you the details?

**Comment by Prajwal-Koirala** [comment]
> I'm using a 25gb vultr instance using CentOS 7 & without the above commands it won't let me connect.
> I can spin you up a new instance if you want to try it ?

Give me 10 mins ill check it out and update back.

**Comment by alpineboi20** [comment]
OK thanks 👍

**Comment by Prajwal-Koirala** [comment]
something came up, can you make a pull.

I am working on something else.

**Comment by Prajwal-Koirala** [comment]
> OK thanks 👍

Hello,
Please feel free to fork and star this repository.
Prajwal

**Comment by Prajwal-Koirala** [comment]
> OK thanks 👍

Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal
