### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by Prajwal-Koirala** [complexorganizations/wireguard-install#127]
@llybin 

I need some help with Arch, please let me know if u can help.

**Comment by llybin** [comment]
ok, ask

Manual here: https://wiki.archlinux.org/index.php/WireGuard

Linux kernel 5.6 will include wireguard module in-build.

**Comment by llybin** [comment]
I see you already use Github Actions. Can create tests there on each distributive. I think for every distro need create new workflow file. Github Actions has matrix, but only for packages inside.

https://hub.docker.com/_/archlinux e.g.

**Comment by Prajwal-Koirala** [comment]
can u please make a pull i have never done that before.
