### ISSUE TITLE
OpenVZ virtualization is not supported (yet).

### ISSUE THREAD

**Issue by zahareevici** [complexorganizations/wireguard-install#130]
**Describe the bug**
Hello, 
Please help me to install the script on VPS wich is not supporting OpenVZ virtualization 

Provider: Strato.de

root@h2795692:/tmp# bash /etc/wireguard/wireguard-server.sh
OpenVZ virtualization is not supported (yet).
**OS: Ubuntu 18.04 Server**

**Comment by Prajwal-Koirala** [comment]
Please use one of the recommended providers

**Comment by zahareevici** [comment]
Moved to another provider, works perfectly.
Is there any chances to connect 2 or more clients on 1 server?

**Comment by Prajwal-Koirala** [comment]
> Moved to another provider, works perfectly.

Hello,
Please feel free to fork and star this repository.
Prajwal

**Comment by Prajwal-Koirala** [comment]
> Moved to another provider, works perfectly.

Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal
