### ISSUE TITLE
Doesn't seem to work for Ubuntu. No idea why

### ISSUE THREAD

**Issue by SuperRaccoon** [complexorganizations/wireguard-install#134]
**Describe the bug**
When created on a server with Ubuntu OS (version 18), Wireguard VPN doesn't seem to be working. No data can get through the connection. Works on Debian. Tested on Vultr

**Comment by Prajwal-Koirala** [comment]
Can u post the debug logs.

**Comment by SuperRaccoon** [comment]
not working for me still somehow, although some packages were updated just recently. I stopped and started wireguard through the script. Would that pick up the latest packages?


debug log:
+ root-check
+ '[' 0 -ne 0 ']'
+ virt-check
++ systemd-detect-virt
+ '[' kvm == openvz ']'
++ systemd-detect-virt
+ '[' kvm == lxc ']'
+ dist-check
+ '[' -e /etc/centos-release ']'
+ '[' -e /etc/debian_version ']'
++ lsb_release -is
+ DISTRO=Ubuntu
+ headless-install
+ '[' '' == y ']'
+ WIREGUARD_PUB_NIC=wg0
+ WG_CONFIG=/etc/wireguard/wg0.conf
+ '[' '!' -f /etc/wireguard/wg0.conf ']'
+ wireguard-next-questions
+ echo 'Looks like Wireguard is already installed.'
Looks like Wireguard is already installed.
+ echo 'What do you want to do?'
What do you want to do?
+ echo '   1) Show WireGuard Interface'
   1) Show WireGuard Interface
+ echo '   2) Start WireGuard Interface'
   2) Start WireGuard Interface
+ echo '   3) Stop WireGuard Interface'
   3) Stop WireGuard Interface
+ echo '   4) Add WireGuard Peer'
   4) Add WireGuard Peer
+ echo '   5) Remove WireGuard Peer'
   5) Remove WireGuard Peer
+ echo '   6) Uninstall WireGuard Interface'
   6) Uninstall WireGuard Interface
+ echo '   7) Update this script'
   7) Update this script
+ echo '   8) Exit'
   8) Exit
+ [[ '' =~ ^[1-8]$ ]]

**Comment by Prajwal-Koirala** [comment]
Can u please delete this VPS from vultr and create a new one and try again.

**Comment by SuperRaccoon** [comment]
Actually it turns out some packages were not updated. I had to do the "sudo apt-get --with-new-pkgs upgrade" because for some reason when I do "sudo apt-get upgrade" it does not upgrade all available packages. It works after that.

Sorry for troubling you. Thank you again for taking the time to look into the issue and I'm sorry for missing it on my end

**Comment by Prajwal-Koirala** [comment]
```
function install-updates() {
  if [ "$DISTRO" == "Ubuntu" ]; then
    apt-get update
    apt-get upgrade -y
    apt-get dist-upgrade -y
    apt-get install linux-virtual -y
    apt-get install linux-headers-$(uname -r) -y
    apt-get install build-essential haveged -y
  elif [ "$DISTRO" == "Debian" ]; then
    apt-get update
    apt-get upgrade -y
    apt-get dist-upgrade -y
    apt-get install linux-headers-$(uname -r) -y
    apt-get install build-essential haveged -y
  fi
  
}

## Install Updates
install-updates

## Function for unattended update to the server
function unattended-upgrades() {
    apt-get install unattended-upgrades apt-listchanges -y
    dpkg-reconfigure unattended-upgrades
}

## Function for unattended-upgrades
unattended-upgrades

## Function For TCP BBR
function tcp-install() {
    modprobe tcp_bbr
    echo "tcp_bbr" >> /etc/modules-load.d/modules.conf
    echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf 
    echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
    sysctl -p
    uname -r
    sysctl net.ipv4.tcp_available_congestion_control
    sysctl net.ipv4.tcp_congestion_control
    sysctl net.core.default_qdisc
    lsmod | grep bbr
}

## TCP BBR
tcp-install
```

This might help in the future.

**Comment by Prajwal-Koirala** [comment]
Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal
