### ISSUE TITLE
Multihop Support

### ISSUE THREAD

**Issue by Mehran** [complexorganizations/wireguard-install#68]
Can you add multihop Support? 
Thanks.

**Comment by LiveChief** [comment]
Any guide or anything??

**Comment by LiveChief** [comment]
Do u hop From the server or client?

**Comment by Mehran** [comment]
Add Script to add support for multihop WireGuard.

**Comment by LiveChief** [comment]
U fucking retard how the fuck do u want me to do that?

I have no idea what the fuck multihopping is in WireGuard

**Comment by Mehran** [comment]
Client connect to Server1 . Server1 connect with WireGuard to Server2

**Comment by LiveChief** [comment]
I'll take a look Into it, but that link that you posted is completely trash
