### ISSUE TITLE
Adding a new peer

### ISSUE THREAD

**Issue by ac2323** [complexorganizations/wireguard-install#98]
**Describe the bug**
When trying to add a peer, I get an error: wireguard-server.sh: line 663: -4: substring expression < 0

**To Reproduce**
1. run sudo bash wireguard-server.sh

**Expected behavior**
Peer to be added

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 18.04.2

**Comment by prajwalkoirala23** [comment]
testing it now.

**Comment by prajwalkoirala23** [comment]
make sure you have "qrencode" installed

`apt-get install qrencode -y`

and make sure your using the latest version of the script.

**Comment by ac2323** [comment]
qrencode is already installed and I am indeed running the latest version of the script

**Comment by prajwalkoirala23** [comment]
dude i tried it and it works perfectly for me, is there any way i can have access to your vps to try and figure out the problem and maybe find the solution for the entire community.

**Comment by ac2323** [comment]
I'm running this on a home server. Is there any other info I could provide that would be useful? My Server config is as follows:

[Interface]
Address = 192.168.2.11/32
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE; iptables -A INPUT -s 192.168.2.11/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
PostDown = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE; iptables -A INPUT -s 192.168.2.11/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
ListenPort = 51820
PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
PresharedKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AllowedIPs = 192.168.100.1/32

**Comment by prajwalkoirala23** [comment]
> I'm running this on a home server. Is there any other info I could provide that would be useful? My Server config is as follows:
> 
> [Interface]
> Address = 192.168.2.11/32
> SaveConfig = true
> PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE; iptables -A INPUT -s 192.168.2.11/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
> PostDown = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE; iptables -A INPUT -s 192.168.2.11/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
> ListenPort = 51820
> PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
> [Peer]
> PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> PresharedKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> AllowedIPs = 192.168.100.1/32

this is not my script, the way u did it is completely wrong.

the allowed ip are wrong and the iptables are wrong the address is wrong.

**Comment by ac2323** [comment]
I started fresh like you suggested and got everything working great. Thank you!

**Comment by ac2323** [comment]
It would be cool if the script also added the new Peer into the Server config, though.

**Comment by prajwalkoirala23** [comment]
if there is a existing server config, it wont work due to the allowed ip being different and alot of things being different its impossible.
